services:
  # Redis for queue management and caching
  redis:
    image: redis:7-alpine
    container_name: pd-entertainme-redis-prod
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  # Server (API)
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
        GIT_SHA: ${GIT_SHA:-latest}
        BUILD_DATE: ${BUILD_DATE}
    container_name: pd-entertainme-server-prod
    restart: unless-stopped
    ports:
      - "8022:8022"
    env_file:
      - ./server/.env.production
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network

volumes:
  redis_data:
    driver: local

networks:
  app-network:
    driver: bridge
    name: pd-entertainme-prod-network
