FROM node:latest

WORKDIR /app
COPY package*.json ./

RUN npm ci --legacy-peer-deps
COPY . .

RUN useradd -m -u 1001 appuser && chown -R appuser:appuser /app
USER appuser

EXPOSE 8000

CMD ["npm", "run", "dev"]
